/**
 * What a first visit costs, here and on the sites this one is measured against.
 *
 * The site's argument is that a claim is worth nothing unless the reader can
 * check it. /verify signs the numbers and lets the browser re-verify them;
 * /security runs real attacks and shows the browser refusing. This is the third
 * one: a performance claim, with the method attached, that anyone can re-run.
 *
 * Two things this deliberately does NOT do, both learned the hard way:
 *
 *   1. It does not report a single run. A page load over the public internet
 *      varies by hundreds of milliseconds between attempts; a one-shot number
 *      measures the network, not the site. Each site is loaded REPEATS times,
 *      and the sites are INTERLEAVED — a,b,a,b — so a slow minute hits every
 *      site rather than whichever happened to go first. The median is reported.
 *   2. It does not claim the comparison is like-for-like in purpose. Apple's
 *      homepage carries video, a product carousel and a store; this one carries
 *      an argument. The measurement is honest about weight and speed and says
 *      nothing about which page is doing the harder job.
 *
 * Usage:  node scripts/compare.mjs [--repeats 5] [--out src/content/compare.json]
 * Needs:  the local site running (npm run dev) and a network connection.
 */
import { chromium } from "playwright";
import { writeFileSync } from "node:fs";

const arg = (k, d) => { const i = process.argv.indexOf(`--${k}`); return i > -1 ? process.argv[i + 1] : d; };
const REPEATS = parseInt(arg("repeats", "5"), 10);
const OUT = arg("out", "");
const LOCAL = process.env.COMPARE_BASE || "http://localhost:8899/";

/* Public marketing homepages of companies whose engineering is widely held up
   as a standard. Named openly: a comparison you cannot reproduce because the
   subjects are secret is not a comparison. */
const SITES = [
  { id: "awalim", name: "عوالِم",  url: LOCAL,                     ours: true },
  { id: "apple",  name: "Apple",   url: "https://www.apple.com/" },
  { id: "stripe", name: "Stripe",  url: "https://stripe.com/" },
  { id: "linear", name: "Linear",  url: "https://linear.app/" },
];

const median = (xs) => { const s = [...xs].sort((a, b) => a - b); const m = s.length >> 1;
  return s.length % 2 ? s[m] : Math.round((s[m - 1] + s[m]) / 2); };

const browser = await chromium.launch();
const runs = Object.fromEntries(SITES.map((s) => [s.id, []]));

for (let r = 0; r < REPEATS; r++) {
  for (const s of SITES) {
    const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
    const page = await ctx.newPage();
    let requests = 0;
    page.on("response", () => requests++);
    const t0 = Date.now();
    try {
      await page.goto(s.url, { waitUntil: "load", timeout: 60000 });
      await page.waitForTimeout(2000);
      const m = await page.evaluate(() => {
        const rs = performance.getEntriesByType("resource");
        const nav = performance.getEntriesByType("navigation")[0];
        const fcp = performance.getEntriesByType("paint").find((p) => p.name === "first-contentful-paint");
        return {
          bytes: rs.reduce((a, x) => a + (x.transferSize || 0), 0) + (nav?.transferSize || 0),
          fcp: fcp ? Math.round(fcp.startTime) : null,
        };
      });
      runs[s.id].push({ ...m, requests, load: Date.now() - t0 });
    } catch { /* a failed load is dropped, not counted as zero — a zero would
                 flatter whichever site failed to answer */ }
    await ctx.close();
  }
}
await browser.close();

const rows = SITES.map((s) => {
  const rs = runs[s.id];
  if (!rs.length) return { ...s, ok: false };
  return {
    id: s.id, name: s.name, ours: !!s.ours, ok: true, samples: rs.length,
    kb: median(rs.map((x) => Math.round(x.bytes / 1024))),
    requests: median(rs.map((x) => x.requests)),
    fcp: median(rs.filter((x) => x.fcp != null).map((x) => x.fcp)),
    load: median(rs.map((x) => x.load)),
  };
}).filter((r) => r.ok);

const us = rows.find((r) => r.ours);
console.log(`\n  ${REPEATS} interleaved runs each · medians\n`);
console.log("  site        weight     requests   first paint   load");
for (const r of rows) {
  console.log(`  ${r.name.padEnd(11)} ${(r.kb + "KB").padEnd(10)} ${String(r.requests).padEnd(10)} ${(r.fcp + "ms").padEnd(13)} ${r.load}ms`);
}
if (us) {
  console.log("");
  for (const r of rows.filter((x) => !x.ours)) {
    console.log(`  vs ${r.name}: ${(r.kb / us.kb).toFixed(1)}× the weight, ${(r.fcp / us.fcp).toFixed(1)}× to first paint`);
  }
}

if (OUT) {
  const payload = {
    _note: "Generated by scripts/compare.mjs — re-run it to check. Medians of interleaved runs; a single run measures the network, not the site.",
    measured: new Date().toISOString().slice(0, 10),
    repeats: REPEATS,
    method: "same Chromium, same viewport (1280×900), same session, sites loaded a,b,c,a,b,c so a slow minute hits all of them",
    caveat: "Weight and speed only. It says nothing about which page is doing the harder job — a product homepage carries video and a store; this one carries an argument.",
    rows,
  };
  writeFileSync(OUT, JSON.stringify(payload, null, 2) + "\n", "utf8");
  console.log(`\n  written to ${OUT}`);
}
